
'use client';
import React from 'react';
import MotionFade from '@/components/motion-fade';
import { Search, ShieldCheck, Globe, School, Zap, Bell, GitBranch, Check, Sparkles, ArrowRight } from 'lucide-react';
import { RoadmapVisual } from './roadmap-visual';
import { VerificationAnimation } from './verification-animation';
import { GlobalOpportunitiesVisual } from './global-opportunities-visual';
import { cn } from '@/lib/utils';
import { Button } from '@/components/ui/button';
import Link from 'next/link';

const features = [
  {
    title: 'AI Job Matching',
    description: 'Our AI delivers explainable, personalized job recommendations that match your complete profile, skills, and career goals—not just keywords.',
    icon: <Sparkles className="w-6 h-6 text-yellow-400" />,
    className: "md:col-span-2 md:row-span-2",
    gradient: "from-yellow-500/20 to-orange-500/20",
    content: (
        <div className="mt-6 relative h-48 rounded-xl bg-slate-950/50 border border-white/5 overflow-hidden group">
            <div className="absolute inset-0 bg-gradient-to-br from-yellow-500/10 to-orange-500/10 opacity-0 group-hover:opacity-100 transition-opacity duration-500" />
            <div className="absolute top-4 left-4 right-4 flex items-center gap-3 p-3 rounded-lg bg-slate-900/80 border border-white/10 backdrop-blur-md">
                <div className="w-10 h-10 rounded-full bg-slate-800 flex items-center justify-center">
                    <span className="text-xl">👨‍💻</span>
                </div>
                <div className="flex-1">
                    <div className="h-2 w-24 bg-slate-700 rounded mb-1.5"></div>
                    <div className="h-1.5 w-16 bg-slate-800 rounded"></div>
                </div>
                <div className="text-green-400 font-bold text-sm">98% Match</div>
            </div>
             <div className="absolute top-20 left-8 right-8 flex items-center gap-3 p-3 rounded-lg bg-slate-900/60 border border-white/5 backdrop-blur-sm scale-95 opacity-60">
                <div className="w-10 h-10 rounded-full bg-slate-800 flex items-center justify-center">
                    <span className="text-xl">🎨</span>
                </div>
                <div className="flex-1">
                    <div className="h-2 w-20 bg-slate-700 rounded mb-1.5"></div>
                    <div className="h-1.5 w-12 bg-slate-800 rounded"></div>
                </div>
                <div className="text-yellow-400 font-bold text-sm">85% Match</div>
            </div>
        </div>
    )
  },
  {
    title: 'Verified Employers',
    description: 'Every employer undergoes multi-layer KYC verification to ensure a safe hiring ecosystem.',
    icon: <ShieldCheck className="w-6 h-6 text-green-400" />,
    className: "md:col-span-1",
    gradient: "from-green-500/20 to-emerald-500/20",
    content: <VerificationAnimation />
  },
  {
    title: 'Global Opportunities',
    description: 'Access government vacancies, private sector roles, and international opportunities in 54+ countries.',
    icon: <Globe className="w-6 h-6 text-blue-400" />,
    className: "md:col-span-1",
    gradient: "from-blue-500/20 to-cyan-500/20",
    content: <GlobalOpportunitiesVisual />
  },
  {
    title: 'Campus & NGO Portals',
    description: 'Dedicated dashboards for colleges and NGOs to manage placements and track impact.',
    icon: <School className="w-6 h-6 text-purple-400" />,
    className: "md:col-span-1",
    gradient: "from-purple-500/20 to-pink-500/20",
  },
  {
    title: 'One-Click Apply',
    description: 'Zekkers pre-fills your entire application using your verified profile and documents.',
    icon: <Zap className="w-6 h-6 text-red-400" />,
    className: "md:col-span-1",
    gradient: "from-red-500/20 to-rose-500/20",
  },
  {
    title: 'AI Skill Roadmaps',
    description: 'Personalized learning paths generated by AI to bridge your skill gaps.',
    icon: <GitBranch className="w-6 h-6 text-indigo-400" />,
    className: "md:col-span-2",
    gradient: "from-indigo-500/20 to-violet-500/20",
    content: (
        <div className="mt-4 flex items-center gap-2 overflow-hidden opacity-70 group-hover:opacity-100 transition-opacity">
            <div className="px-3 py-1 rounded-full bg-slate-800 border border-white/10 text-xs text-slate-300">React</div>
            <ArrowRight className="w-4 h-4 text-slate-600" />
            <div className="px-3 py-1 rounded-full bg-slate-800 border border-white/10 text-xs text-slate-300">Next.js</div>
            <ArrowRight className="w-4 h-4 text-slate-600" />
            <div className="px-3 py-1 rounded-full bg-slate-800 border border-white/10 text-xs text-slate-300">TypeScript</div>
            <ArrowRight className="w-4 h-4 text-slate-600" />
            <div className="px-3 py-1 rounded-full bg-green-500/20 border border-green-500/30 text-xs text-green-400">Hired</div>
        </div>
    )
  },
];

export default function FeaturesSection() {
    return (
        <section id="features" className="px-6 md:px-12 py-24 bg-background relative overflow-hidden">
             {/* Background Gradients */}
            <div className="absolute top-0 left-1/4 w-96 h-96 bg-primary/10 rounded-full blur-3xl pointer-events-none" />
            <div className="absolute bottom-0 right-1/4 w-96 h-96 bg-accent/10 rounded-full blur-3xl pointer-events-none" />

            <div className="max-w-7xl mx-auto relative z-10">
                <MotionFade>
                    <div className="text-center max-w-2xl mx-auto mb-16">
                        <h2 className="text-3xl md:text-5xl font-bold text-white mb-6">
                            Why <span className="text-transparent bg-clip-text bg-gradient-to-r from-primary to-accent">Zekkers?</span>
                        </h2>
                        <p className="text-lg text-muted-foreground">
                            Trusted, intelligent, and built for the future of work.
                        </p>
                    </div>
                </MotionFade>

                <div className="grid grid-cols-1 md:grid-cols-3 gap-6 auto-rows-[minmax(180px,auto)]">
                    {features.map((feature, index) => (
                        <MotionFade key={feature.title} delay={index * 0.1}>
                            <div className={cn(
                                "group relative h-full p-6 rounded-3xl bg-card border border-white/5 overflow-hidden hover:border-primary/20 transition-all duration-300 hover:shadow-2xl hover:shadow-primary/5",
                                feature.className
                            )}>
                                <div className={cn(
                                    "absolute inset-0 bg-gradient-to-br opacity-0 group-hover:opacity-100 transition-opacity duration-500",
                                    feature.gradient
                                )} />
                                
                                <div className="relative z-10 flex flex-col h-full">
                                    <div className="flex items-start justify-between mb-4">
                                        <div className="p-3 rounded-2xl bg-background/50 border border-white/5 text-white group-hover:scale-110 transition-transform duration-300">
                                            {feature.icon}
                                        </div>
                                    </div>
                                    
                                    <h3 className="text-xl font-bold text-white mb-2">{feature.title}</h3>
                                    <p className="text-muted-foreground text-sm leading-relaxed mb-auto">
                                        {feature.description}
                                    </p>
                                    
                                    {feature.content}
                                </div>
                            </div>
                        </MotionFade>
                    ))}
                </div>
            </div>
        </section>
    );
}
