
import { PlaceHolderImages } from "@/lib/placeholder-images";
import { Candidate } from "@/types/candidate";

export const MOCK_CANDIDATES: Candidate[] = [
  {
    id: 'cand-1',
    name: 'Anjali Sharma',
    email: 'anjali.sharma@example.com',
    location: 'Bengaluru, India',
    experienceYears: 2,
    jobId: 'priv-1',
    jobAppliedFor: 'Frontend Developer',
    skills: ['React', 'TypeScript', 'Next.js', 'TailwindCSS', 'Figma'],
    missingSkills: ['GraphQL'],
    profileStrength: 88,
    aiMatchScore: 92,
    resumeURL: '#',
    status: 'Screening',
    appliedAt: '2024-07-28T10:00:00Z',
    avatar: PlaceHolderImages.find(p => p.id === 'avatar1')?.imageUrl,
    education: 'B.Tech in Computer Science',
    assessmentStatus: 'Passed',
    assessmentScore: 85,
    interviewStatus: 'Scheduled',
    interviewDate: '2024-08-05T14:00:00Z',
    visaStatus: 'Visa-Ready'
  },
  {
    id: 'cand-2',
    name: 'Rohan Verma',
    email: 'rohan.verma@example.com',
    location: 'Pune, India',
    experienceYears: 5,
    jobId: 'priv-2',
    jobAppliedFor: 'Senior Backend Engineer',
    skills: ['Node.js', 'PostgreSQL', 'Docker', 'Kubernetes', 'AWS'],
    missingSkills: ['Go'],
    profileStrength: 95,
    aiMatchScore: 89,
    resumeURL: '#',
    status: 'Interview',
    appliedAt: '2024-07-25T09:00:00Z',
    avatar: PlaceHolderImages.find(p => p.id === 'avatar2')?.imageUrl,
    education: 'M.Tech in Computer Science',
    assessmentStatus: 'Completed',
    assessmentScore: 78,
    interviewStatus: 'Scheduled'
  },
  {
    id: 'cand-3',
    name: 'Priya Patel',
    email: 'priya.patel@example.com',
    location: 'Remote',
    experienceYears: 1,
    jobId: 'priv-1',
    jobAppliedFor: 'UX/UI Designer',
    skills: ['Figma', 'Adobe XD', 'User Research', 'Prototyping'],
    missingSkills: ['Webflow'],
    profileStrength: 75,
    aiMatchScore: 81,
    resumeURL: '#',
    status: 'Applied',
    appliedAt: '2024-07-29T14:00:00Z',
    avatar: PlaceHolderImages.find(p => p.id === 'avatar3')?.imageUrl,
    education: 'B.Des in Communication Design',
    assessmentStatus: 'Pending',
    interviewStatus: 'Not Scheduled'
  },
];
