

import { Job } from "@/types/job";

export const MOCK_JOBS: Job[] = [
    // Government Jobs
    { id: 'gov-1', title: 'Clerk — Revenue Dept', company: 'Govt. of Maharashtra', location: 'Mumbai', department: 'Revenue', type: 'onsite', salaryMin: 300000, salaryMax: 450000, experienceMin: 0, experienceMax: 2, skills: ['MS Office', 'Typing'], qualifications: ['12th Pass'], postedAt: new Date(Date.now() - 5*24*3600*1000), category: 'government', country: 'India', status: 'published', currency: 'INR', employerId: 'mock-gov-employer' },
    { id: 'gov-2', title: 'Stenographer Grade C', company: 'Staff Selection Commission', location: 'Delhi', department: 'Central Secretariat', type: 'onsite', salaryMin: 400000, salaryMax: 550000, experienceMin: 0, experienceMax: 1, skills: ['Stenography', 'Typing'], qualifications: ['12th Pass'], postedAt: new Date(Date.now() - 10*24*3600*1000), category: 'government', country: 'India', status: 'published', currency: 'INR', employerId: 'mock-gov-employer' },
    { id: 'gov-3', title: 'Junior Engineer (Civil)', company: 'Public Works Department', location: 'Chennai', department: 'Public Works', type: 'onsite', salaryMin: 500000, salaryMax: 700000, experienceMin: 1, experienceMax: 3, skills: ['AutoCAD', 'Surveying'], qualifications: ['Diploma in Civil Engg.'], postedAt: new Date(Date.now() - 15*24*3600*1000), category: 'government', country: 'India', status: 'published', currency: 'INR', employerId: 'mock-gov-employer' },
    { id: 'gov-4', title: 'Railway Constable', company: 'Railway Protection Force', location: 'Kolkata', department: 'Railways', type: 'onsite', salaryMin: 250000, experienceMin: 0, experienceMax: 0, skills: ['Physical Fitness'], qualifications: ['10th Pass'], postedAt: new Date(Date.now() - 20*24*3600*1000), category: 'government', country: 'India', status: 'published', currency: 'INR', employerId: 'mock-gov-employer' },

    // Private Jobs
    { id: 'priv-1', title: 'Frontend Engineer', company: 'ZekkTech', location: 'Bengaluru', type: 'hybrid', salaryMin: 600000, salaryMax: 1200000, experienceMin: 1, experienceMax: 5, skills: ['React','TypeScript','CSS'], qualifications: ['B.Tech'], postedAt: new Date(Date.now() - 2*24*3600*1000), category: 'private', country: 'India', status: 'published', currency: 'INR', employerId: 'mock-private-employer' },
    { id: 'priv-2', title: 'Data Analyst', company: 'InfoLabs', location: 'Pune', type: 'remote', salaryMin: 400000, salaryMax: 800000, experienceMin: 0, experienceMax: 3, skills: ['SQL','Excel','Python'], qualifications: ['B.Sc'], postedAt: new Date(Date.now() - 8*24*3600*1000), category: 'private', country: 'India', status: 'published', currency: 'INR', employerId: 'mock-private-employer' },
    { id: 'priv-3', title: 'Product Manager', company: 'InnovateHub', location: 'Hyderabad', type: 'onsite', salaryMin: 1500000, salaryMax: 2500000, experienceMin: 4, experienceMax: 8, skills: ['Agile', 'Roadmapping', 'Market Research'], qualifications: ['MBA', 'B.Tech'], postedAt: new Date(Date.now() - 3*24*3600*1000), category: 'private', country: 'India', status: 'published', currency: 'INR', employerId: 'mock-private-employer' },
    { id: 'priv-4', title: 'Digital Marketing Intern', company: 'Growthify', location: 'Remote', type: 'internship', salaryMin: 15000, salaryMax: 25000, experienceMin: 0, experienceMax: 1, skills: ['SEO', 'Social Media Marketing', 'Content Writing'], qualifications: ['Any Graduate'], postedAt: new Date(Date.now() - 1*24*3600*1000), category: 'private', country: 'India', status: 'published', currency: 'INR', employerId: 'mock-private-employer' },
    { id: 'priv-5', title: 'DevOps Engineer', company: 'CloudNimbus', location: 'Noida', type: 'hybrid', salaryMin: 900000, salaryMax: 1600000, experienceMin: 3, experienceMax: 6, skills: ['AWS', 'Docker', 'Kubernetes', 'CI/CD'], qualifications: ['B.Tech', 'MCA'], postedAt: new Date(Date.now() - 12*24*3600*1000), category: 'private', country: 'India', status: 'published', currency: 'INR', employerId: 'mock-private-employer' },
    
    // International Jobs
    { id: 'intl-1', title: 'Fullstack Developer', company: 'GlobalSoft Inc', location: 'Berlin', country: 'Germany', type: 'remote', salaryMin: 70000, salaryMax: 90000, experienceMin: 2, experienceMax: 6, skills: ['Node','React', 'GraphQL'], qualifications: ['B.Tech', 'M.Sc Computer Science'], postedAt: new Date(Date.now() - 1*24*3600*1000), category: 'international', currency: 'EUR', status: 'published', employerId: 'mock-intl-employer' },
    { id: 'intl-2', title: 'QA Engineer', company: 'US Tech', location: 'New York', country: 'USA', type: 'hybrid', salaryMin: 80000, salaryMax: 130000, experienceMin: 3, experienceMax: 7, skills: ['Selenium','API Testing', 'Cypress'], qualifications: ['B.Sc in CS or related field'], postedAt: new Date(Date.now() - 7*24*3600*1000), category: 'international', currency: 'USD', status: 'published', employerId: 'mock-intl-employer' },
    { id: 'intl-3', title: 'Senior Golang Developer', company: 'EuroDev', location: 'Amsterdam', country: 'Netherlands', type: 'remote', salaryMin: 85000, salaryMax: 110000, experienceMin: 5, experienceMax: 10, skills: ['Go', 'Microservices', 'PostgreSQL'], qualifications: ['B.S. or M.S. in Computer Science'], postedAt: new Date(Date.now() - 4*24*3600*1000), category: 'international', currency: 'EUR', status: 'published', employerId: 'mock-intl-employer' },
    { id: 'intl-4', title: 'Project Manager (Construction)', company: 'Dubai Infra', location: 'Dubai', country: 'UAE', type: 'onsite', salaryMin: 25000, salaryMax: 35000, experienceMin: 8, experienceMax: 15, skills: ['Project Management', 'Primavera P6', 'Civil Engineering'], qualifications: ['B.E. in Civil Engineering'], postedAt: new Date(Date.now() - 18*24*3600*1000), category: 'international', currency: 'AED', status: 'published', employerId: 'mock-intl-employer' },
    { id: 'intl-5', title: 'Registered Nurse', company: 'NHS Trust', location: 'London', country: 'UK', type: 'onsite', salaryMin: 35000, salaryMax: 45000, experienceMin: 2, experienceMax: 10, skills: ['Patient Care', 'Clinical Skills'], qualifications: ['B.Sc Nursing', 'NMC Registration'], postedAt: new Date(Date.now() - 9*24*3600*1000), category: 'international', currency: 'GBP', status: 'published', employerId: 'mock-intl-employer' },
    
    // More Private Jobs
    { id: 'priv-6', title: 'Graphic Designer', company: 'CreativeMinds', location: 'Jaipur', type: 'remote', salaryMin: 300000, salaryMax: 600000, experienceMin: 2, experienceMax: 5, skills: ['Adobe Creative Suite', 'Illustration', 'Branding'], qualifications: ['Degree in Design'], postedAt: new Date(Date.now() - 6*24*3600*1000), category: 'private', country: 'India', status: 'published', currency: 'INR', employerId: 'mock-private-employer' },
    { id: 'priv-7', title: 'Human Resources Manager', company: 'PeopleFirst Corp', location: 'Ahmedabad', type: 'onsite', salaryMin: 800000, salaryMax: 1500000, experienceMin: 5, experienceMax: 10, skills: ['Recruitment', 'Employee Relations', 'HR Policy'], qualifications: ['MBA in HR'], postedAt: new Date(Date.now() - 14*24*3600*1000), category: 'private', country: 'India', status: 'published', currency: 'INR', employerId: 'mock-private-employer' },
    { id: 'priv-8', title: 'Mechanical Engineer', company: 'AutoWorks', location: 'Chennai', type: 'onsite', salaryMin: 500000, salaryMax: 900000, experienceMin: 2, experienceMax: 5, skills: ['SolidWorks', 'AutoCAD', 'Thermodynamics'], qualifications: ['B.E. Mechanical'], postedAt: new Date(Date.now() - 11*24*3600*1000), category: 'private', country: 'India', status: 'published', currency: 'INR', employerId: 'mock-private-employer' },
  ];
