import {
  LayoutGrid,
  Briefcase,
  Users,
  BarChart2,
  MessageSquare,
  Settings,
  CreditCard,
  Building,
  Plug,
  ShieldCheck,
  Handshake,
  Globe,
  LifeBuoy,
  Kanban,
  Sparkles,
  Bell,
} from 'lucide-react';
import React from 'react';

export const menuItems = [
  {
    key: 'overview',
    label: 'Overview',
    to: '/employer-dashboard',
    icon: React.createElement(LayoutGrid, { size: 20 }),
    exact: true,
  },
  {
    key: 'jobs',
    label: 'Job Management',
    icon: React.createElement(Briefcase, { size: 20 }),
    to: '/employer-dashboard/jobs',
    subItems: [
      { key: 'post-new', label: 'Post a Job', to: '/employer-dashboard/jobs/create' },
      { key: 'manage', label: 'Manage Jobs', to: '/employer-dashboard/jobs' },
      { key: 'drafts', label: 'Drafts', to: '/employer-dashboard/jobs/drafts' },
      { key: 'ai-generator', label: 'AI JD Generator', to: '/employer-dashboard/jobs/ai-generator', icon: React.createElement(Sparkles, { size: 16 }) },
    ],
  },
  {
    key: 'candidates',
    label: 'Candidate Management',
    to: '/employer-dashboard/candidates',
    icon: React.createElement(Users, { size: 20 }),
    subItems: [
      { key: 'list', label: 'Candidate List', to: '/employer-dashboard/candidates' },
      { key: 'shortlisted', label: 'Shortlisted', to: '/employer-dashboard/candidates/shortlisted' },
      { key: 'saved', label: 'Saved', to: '/employer-dashboard/candidates/saved' },
      { key: 'ai-finder', label: 'AI Candidate Finder', to: '/employer-dashboard/candidates/ai-finder', icon: React.createElement(Sparkles, { size: 16 }) },
    ],
  },
  { key: 'ats', label: 'ATS', to: '/employer-dashboard/ats', icon: React.createElement(Kanban, { size: 20 }) },
  { key: 'assessments', label: 'Assessment Center', to: '/employer-dashboard/assessments', icon: React.createElement(ShieldCheck, { size: 20 }) },
  { key: 'messages', label: 'Messages & Communication', to: '/employer-dashboard/messages', icon: React.createElement(MessageSquare, { size: 20 }) },
  { key: 'notifications', label: 'Notifications', to: '/employer-dashboard/notifications', icon: React.createElement(Bell, { size: 20 }) },
  {
    key: 'company-profile',
    label: 'Company Profile',
    icon: React.createElement(Building, { size: 20 }),
    to: '/employer-dashboard/settings',
    subItems: [
      { key: 'profile', label: 'Basic Info', to: '/employer-dashboard/settings' },
      { key: 'branding', label: 'Branding', to: '/employer-dashboard/settings/branding' },
      { key: 'kyc', label: 'KYC & Verification', to: '/employer-dashboard/settings/kyc' },
      { key: 'team', label: 'Team Members', to: '/employer-dashboard/settings/team' },
    ],
  },
  { key: 'analytics', label: 'Analytics & Insights', to: '/employer-dashboard/analytics', icon: React.createElement(BarChart2, { size: 20 }) },
  { key: 'partners', label: 'College & NGO Partners', to: '/employer-dashboard/partnerships', icon: React.createElement(Handshake, { size: 20 }) },
  { key: 'global-hiring', label: 'Global Hiring', to: '/employer-dashboard/global-hiring', icon: React.createElement(Globe, { size: 20 }) },
  { key: 'billing', label: 'Billing & Plans', to: '/employer-dashboard/billing', icon: React.createElement(CreditCard, { size: 20 }) },
  { key: 'integrations', label: 'Integrations', to: '/employer-dashboard/integrations', icon: React.createElement(Plug, { size: 20 }) },
  { key: 'settings', label: 'Settings', to: '/employer-dashboard/settings', icon: React.createElement(Settings, { size: 20 }) },
  { key: 'support', label: 'Support & Help', to: '/employer-dashboard/support', icon: React.createElement(LifeBuoy, { size: 20 }) },
];
